require('dotenv').config();
const domain = process.env.MAILER_DOMAIN;
const apiKey = process.env.MAILER_API_KEY;

const mailer = require('mailgun-js')({ domain: domain, apiKey: apiKey });

/**
 * @param {string} email e-mail address to send mailer too
 * @param {string} hash has generated by uuid
 */

module.exports = {
  sendPasswordResetEmail: async (email, hash) => {
    const data = {
      from: `no-reply@${domain} <no-reply@davesnews.one>`,
      to: `${email}`,
      subject: 'NewsOne password recovery',
      // eslint-disable-next-line max-len
      html: `<body> <p>Please use <a href="http://${domain}/recover/${hash}>this link</a> to recover your password</p></body>`,
    };
    try {
      return await mailer.messages().send(data);
    } catch (exception) {
      console.log(exception);
    }
  },
};
