require('dotenv').config();
const domain = process.env.MAILER_DOMAIN;
const friendlyDomain = process.env.MAILER_FRIENDLY_DOMAIN;
const apiKey = process.env.MAILER_API_KEY;

const mailer = require('mailgun-js')({ domain: domain, apiKey: apiKey });

/**
 * @param {string} email e-mail address to send mailer too
 * @param {string} hash has generated by uuid
 */

module.exports = {
  sendPasswordResetEmail: async (email, hash) => {
    const data = {
      from: `no-reply@${friendlyDomain} <no-reply@${friendlyDomain}>`,
      to: `${email}`,
      subject: 'NewsOne password recovery',
      // eslint-disable-next-line max-len
      html: `<html><body> <p>Please use http://${friendlyDomain}/recover/${hash} to recover your password</p></body></html>`,
    };
    try {
      return await mailer.messages().send(data);
    } catch (exception) {
      console.log(exception);
    }
  },
};
